import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from './components/Navbar'
import Typical from 'react-typical'
import Typing from './components/Typing'
import 'bootstrap/dist/css/bootstrap.css'
import './tailwind.config'
import Link from 'next/link'


export default function Home() {

  



  return (
    <div className={styles.container}>
        <Navbar/>
      <Head>
        <title>GeekLords</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    

      <main className={styles.main}>
        
        <h1 className={styles.title}>  
                

              <Typing />
            </h1>
            

        <p className={styles.description}>
          Your Coding Buddy{' '}
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
         <Link href={'/dashboard'} ><a href="" className={`${styles.card} shadow`}>
            <h2>Dashboard &rarr;</h2>
            <p>See your Activities and ranking.</p>
          </a></Link>

          <Link href={'/todaysquestions'} ><a href="" className={`${styles.card} shadow`}>
            <h2>Today's Problems &rarr;</h2>
            <p>View and solve today's problem.</p>
          </a></Link>

          <Link href={'/previousproblems'}><a
            href=""
            className={`${styles.card} shadow`}
          >
            <h2>Previous Problems &rarr;</h2>
            <p>See all the previously posted weekly problem statements.</p>
          </a>
          </Link>
          <a
            href=""
            className={`${styles.card} shadow`}
          >
            <h2>Solutions &rarr;</h2>
            <p>
              View the solutions of each and every problem which is posted previously.
            </p>
          </a>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {' '}
          {/* <span className={styles.logo}> */}
               <span style={{color:"#062c51"}}>&nbsp;&nbsp;  Axis Colleges CSE Department </span>
          {/* </span> */}
        </a>
      </footer>
    </div>

  
  )
}
