import Head from 'next/head'
import styles from '../styles/Home.module.css'
import tcss from '../styles/tcss.module.css'
import Navbar from './components/Navbar'
import 'bootstrap/dist/css/bootstrap.css'
import './tailwind.config'
import mongoose from 'mongoose'
import Questions from "../models/Questions"
import Link from 'next/link'
import moment from 'moment'



const Todaysquestions = ({ questions }) => {
    console.log(questions)
  return (
    <>
   <div className={styles.container}>
        <Navbar/>
      <Head>
        <title>GeekLords</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    

      <main className={styles.main}>
        
        <h1 className={`${styles.title} my-4 py-4`}>  
                
                Today's questions
              
            </h1>
            

        


        <div className="row py-4">

            {questions.map((item)=>{

                
                
                  return (
                    <Link passHref={true} key={item._id} href={`/questions/${item._id}`}>
            <div className="col-md-3 mx-auto">
               <div className={ `${tcss.qimg} shadow`}>
                   Question 1 <span className={tcss.topic}> <b>Topic :</b> <span>Array</span> </span> 
               </div>
            </div>
            </Link>
                )
                
               
             })}

        </div>

      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {' '}
          {/* <span className={styles.logo}> */}
               <span style={{color:"#062c51"}}>&nbsp;&nbsp;  Axis Colleges CSE Department </span>
          {/* </span> */}
        </a>
      </footer>
    </div>
    
    </>
  )
}

export async function getServerSideProps() {


    if(!mongoose.connections[0].readyState){
        await mongoose.connect(process.env.MONGO_URI)
    }
    // Fetch data from external API
    // let dt = item.createdAt.substr(0,10);
                var today = new Date();
                var dd = String(today.getDate()).padStart(2, '0');
                var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
                var yyyy = today.getFullYear();
                
                today = yyyy + '-' + mm + '-' + dd;
                console.log(today)
    let questions = await Questions.find({pdate : `${today}` });
 
    console.log(questions)
  
    // Pass data to the page via props
    return { props: {questions : JSON.parse(JSON.stringify(questions))}}
  }
  


export default Todaysquestions